### ISSUE TITLE
[Bug]OptunaSweeper sample does not work with Hydra=1.2.0

### ISSUE THREAD

**Issue by mrkm99** [facebookresearch/hydra#2313]
I tried OptunaSweeper following the official tutorial, but an error occurred.
Site:https://hydra.cc/docs/next/plugins/optuna_sweeper/
command:```python example/sphere.py --multirun 'x=interval(-5.0, 5.0)' 'y=interval(0, 10)'```
Error encountered
```
In 'config': ConfigKeyError raised while composing config:
Key 'max_failure_rate' not in 'OptunaSweeperConf'
    full_key: hydra.sweeper.max_failure_rate
    object_type=OptunaSweeperConf

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
OS:Windows10
Python:3.10.5
Library Version:
```
hydra-core                1.2.0
hydra-optuna-sweeper      1.2.0
```

**Comment by Jasha10** [comment]
This should be fixed if you use the latest version of the `hydra-optuna-sweeper` package from pypi.

**Comment by mrkm99** [comment]
Thanks Jasha10.
I tried with the latest version but the error still occurs.
I was able to avoid the error by removing max_failure_rate in config.
If this item is not important, it should be removed from the sample conf/config.yaml.

**Comment by Jasha10** [comment]
I see. Sorry about that.

**Comment by praksharma** [comment]
The error is still there. I was trying this example from the official repo. https://github.com/facebookresearch/hydra/blob/main/plugins/hydra_optuna_sweeper/example/sphere.py

The error is:

```
[s.1915438@sl2(sunbird) testing]$ python main.py 
In 'config': ConfigKeyError raised while composing config:
Key 'max_failure_rate' not in 'OptunaSweeperConf'
    full_key: hydra.sweeper.max_failure_rate
    object_type=OptunaSweeperConf
```

Here is my hydra versions:
```
[s.1915438@sl2(sunbird) testing]$ pip list | grep hydra
hydra-core                    1.2.0
hydra-optuna-sweeper          1.2.0
hydra-submitit-launcher       1.2.0
```

**Comment by mmcdermott** [comment]
Can a fresh version be pushed to fix this? It is very confusing that this parameter is not in the latest stable version.

**Comment by omry** [comment]
This is fixed and available in the `hydra-optuna-sweeper` 1.4.0.dev6 prerelease:

```shell
pip install --upgrade --pre hydra-optuna-sweeper
```
